#pragma once

#include <sstream>
#include <WICTextureLoader.h>
#include <Box2D\Box2D.h>

#include "SList.h"
#include "Vector.h"
#include "Stack.h"
#include "HashMap.h"
#include "Common.h"
#include "Datum.h"
#include "RTTI.h"
#include "Scope.h"
#include "IXmlParseHelper.h"
#include "XmlParseMaster.h"

#include "IntegerXmlParseHelper.h"
#include "FloatXmlParseHelper.h"
#include "VectorXmlParseHelper.h"
#include "MatrixXmlParseHelper.h"
#include "TableXmlParseHelper.h"
#include "StringXmlParseHelper.h"
#include "EntityXmlParseHelper.h"
#include "SectorXmlParseHelper.h"
#include "WorldXmlParseHelper.h"
#include "ActionXmlParseHelper.h"
#include "ReactionXmlParseHelper.h"
#include "TileXmlParseHelper.h"
#include "SoundParser.h"

#include "FooSharedData.h"
#include "TableSharedData.h"
#include "SymbolSharedData.h"
#include "SoundSharedData.h"

#include "EventSubscriber.h"
#include "EventPublisher.h"
#include "Event.h"
#include "EventQueue.h"

#include "Factory.h"

#include "GameClock.h"
#include "GameTime.h"

#include "Entity.h"
#include "Sector.h"
#include "World.h"
#include "WorldState.h"
#include "ActionContainer.h"

#include "Camera.h"
#include "Sprite.h"
#include "ColorHelper.h"
#include "Common.h"
#include "DrawableGameComponent.h"
#include "Game.h"
#include "GameClock.h"
#include "GameComponent.h"
#include "GameException.h"
#include "GameTime.h"
#include "Keyboard.h"
#include "MatrixHelper.h"
#include "RenderingGame.h"
#include "RenderTarget.h"
#include "RTTI.h"
#include "ServiceContainer.h"
#include "Utility.h"
#include "VectorHelper.h"
#include "VertexDeclarations.h"

#include "ActionMovePlayer.h"
#include "ActionFlipPlayer.h"
#include "ActionSpriteDraw.h"
#include "ActionSpriteUpdate.h"
#include "EntityTile.h"
#include "EntityPlayer.h"
#include "EntityInputHandler.h"
#include "EntityMovable.h"
#include "EntityText.h"
#include "EntityBackground.h"
#include "LevelParser.h"

#include "Animation.h"
#include "fmod.hpp"
#include "SoundManager.h"
